### ISSUE TITLE
Issue with -ldl on a FreeBSD system

### ISSUE THREAD

**Issue by scollin** [eduardok/libsmbclient-php#14]
I just had to install libsmbclient-php on a FreeBSD system (to be correct, on a Jail on a FreeNAS system).
The problem is, on FreeBSD, there is no such library. So the test for smbc_open will fail due to this.
Error message : `configure: error: Could not find libsmbclient.so or symbol smbc_open. Check config.log for more information.`

The solution to this problem is pretty simple, just remove -ldl in this part of the configure file (generated after the "phpize" command)  : 
>save_old_LDFLAGS=$LDFLAGS
>  ac_stuff="
>      -lsmbclient -lm -ldl
>    "

And now, the ./configure should be ok

**Comment by aklomp** [comment]
Thanks for the heads up. Commit 7f05510 should have fixed this. It removes the -lm and -ldl flags from config.m4, which were both unnecessary to begin with.

**Comment by pcseed** [comment]
I use FreeBSD 9 , installed samba-libsmbclient.

I download libsmbclient-php-0.7.0 & try to compile it.

phpize ok
./configure not ok , same error.

>checking for smbc_open in -lsmbclient... no
configure: error: Could not find libsmbclient.so or symbol smbc_open. Check config.log for more information.

**Comment by aklomp** [comment]
It seems that linking against ` -lsmbclient` does not work on your system. Can you check that libsmbclient.so can be found somewhere in a default library dir? Can you post the relevant parts of `config.log` that show the linking failing?

Does this work on your system? (Compiling a toy program and linking it against lsmbclient):

```sh
echo 'main(){}' | cc -x c - -o /dev/null -lsmbclient
```

**Comment by pcseed** [comment]
I found libsmbclient.so

    /usr/local/lib/libsmbclient.so

Here is config.log
>configure:4242: checking for libsmbclient.h in default paths
configure:4247: result: found in /usr/local/include
configure:4355: checking for smbc_open in -lsmbclient
configure:4380: cc -o conftest -g -O2   -lsmbclient conftest.c -lsmbclient   >&5
/usr/bin/ld: cannot find -lsmbclient
configure:4380: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
|
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char smbc_open ();
| int
| main ()
| {
| return smbc_open ();
|   ;
|   return 0;
| }
configure:4389: result: no
configure:4461: error: Could not find libsmbclient.so or symbol smbc_open. Check config.log for more information.

I run echo 'main(){}' | cc -x c - -o /dev/null -lsmbclient , here is the result.

    /usr/bin/ld: cannot find -lsmbclient

**Comment by aklomp** [comment]
Looks like `/usr/local/lib` is not part of your linker's search path. I suspect this example will work, because it adds `/usr/local/lib` as a search path:

```sh
echo 'main(){}' | cc -x c - -o /dev/null -L/usr/local/lib -lsmbclient
```

Please refer to your linker's documentation to see how to add a path to its search path. It probably involves adding an entry to `/etc/ld.so.conf`.

**Comment by pcseed** [comment]
The example is worked.

I add /etc/ld.so.conf , but not work.

    /usr/lib
    /usr/local/lib


So I just edit configure,add
>-L/usr/local/lib

before

> -lsmbclient

It's will sucess , Thanks.

**Comment by H4ndl3** [comment]
You have to run
>setenv LDFLAGS -L/usr/local/lib
before
>./configure
and everything will work just fine.

**Comment by yaizawa2e** [comment]
I succeed configure under FreeBSD 10.1.
When run configure, I added `--with-libsmbclient=/usr/local`.

```
% uname -a
FreeBSD owncloud 10.1-RELEASE FreeBSD 10.1-RELEASE #0 r274401: Tue Nov 11 21:02:49 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
% pkg info | grep libsmbclient
samba36-libsmbclient-3.6.25_2  Shared lib from the samba package
% phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
% ./configure --with-libsmbclient=/usr/local
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... amd64-unknown-freebsd10.1
checking host system type... amd64-unknown-freebsd10.1
checking target system type... amd64-unknown-freebsd10.1
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/20131226
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking whether to enable smbclient support... yes, shared
checking for libsmbclient support... yes, shared
checking for smbc_setOptionUseNTHash in -lsmbclient... no
checking for smbc_setPort in -lsmbclient... no
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... freebsd10.1 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
```
