### ISSUE TITLE
Current PHP License not suitable for anything else but PHP

### ISSUE THREAD

**Issue by DavidPrevot** [eduardok/libsmbclient-php#15]
Hi,

The old (pre 3.x) version of PHP License this source code is using, is not really usable for anything else than PHP itself. Basically this license talks only about PHP, the PHP Group, and includes Zend Engine, so its not applicable to anything else.

> Ref: https://ftp-master.debian.org/REJECT-FAQ.html

It would be nice to change the license to something like LGPL or BSD that would properly achieve the freeness of the code as you see fit.

**Comment by aklomp** [comment]
I strongly agree, the PHP license is unsuitable for this project for the exact reasons you mentioned. It should definitely be changed to a mainstream open source license that fits a library or component, such as LGPL, AGPL, BSD or MIT.

I guess Eduardo and I (the current maintainers) can agree on a license, but we should also get permission from the original author, @matthewg.

**Comment by matthewg** [comment]
Hey, cool, I didn't realize anyone was maintaining this! Yes, you have my blessing to change this to any open source license you'd like.

**Comment by aklomp** [comment]
Thanks, @matthewg! This project remains relevant since PHP still does not have any Samba bindings. It's slowly getting traction now that OwnCloud is adopting it. It's just a bridge, but a useful one.

@eduardok, how about we relicense this repo under the 2-clause BSD license and release 0.7.0? I'm a fan of the 2-clause BSD because it's really simple and very liberal, also for commercial use. I feel that's the right stance for middleware like this, where the goal is to offer a useful piece of infrastructure without being opinionated.

**Comment by matthewg** [comment]
Nifty, happy hacking! (FWIW, I also wrote https://github.com/matthewg/Zevils/tree/master/php-smb back in 2003, a pure-PHP implementation of the protocol, but let's just say that it's more than a little untested and feature-incomplete.)

**Comment by eduardok** [comment]
Hi Matthew, good to hear from you :)
If I remember right, I didn't want to bother you back in 2009 when I found your subversion repo with libsmbclient-php, so I just got github to import it here. Wasn't doing anything too big anyway. It was Alfred who finally modernized it :)
I must have seen php-smb if it was open back then.
Anyway, I'm actually back to working for the company I was with in 2009 when I did this! I start next Tuesday, but responsibilities increased now, not sure I'll be able to help much (and yeah, my C is still weak) :P 

2-clause BSD sounds nice Alfred, I agree. Please commit with Matthew's Sign-off-by and mine (I guess these messages will serve as the Ack).

**Comment by aklomp** [comment]
Changed to the BSD 2-clause license. Version 0.7.0 (coming soon) will be the first release under the new license.

**Comment by DavidPrevot** [comment]
> Changed to the BSD 2-clause license.

Thank you to all involved persons, for taking this request into account
seriously, and acting on it so quickly!

Regards

David
