### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by remicollet** [eduardok/libsmbclient-php#19]
Whatever the license is (PHP or BSD), please add a LICENSE file which is mandatory, per license term, for redistribution.

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

**Comment by aklomp** [comment]
See Issue #15.

**Comment by aklomp** [comment]
Should close after adding the actual LICENSE file.

**Comment by aklomp** [comment]
The project has been relicensed under the BSD 2-clause license, and a `LICENSE` file included in the project root.
