### ISSUE TITLE
Extension name

### ISSUE THREAD

**Issue by remicollet** [eduardok/libsmbclient-php#21]
For discussion:
Extension name is libsmbclient, but libsmbclient.so is not a good name, and create confusion with the library.

Even "autotool" don't like it.

    $ touch libsmbclient.c
    $ make
    *** Warning: Linking the shared library libsmbclient.la against the loadable module
    *** libsmbclient.so is not portable!
    
    *** Warning: Linking the shared library libsmbclient.la against the loadable module
    *** libsmbclient.so is not portable!
    libtool: link: rm -fr  .libs/libsmbclient.la .libs/libsmbclient.lai .libs/libsmbclient.so
    libtool: link: cc -shared  -fPIC -DPIC  .libs/libsmbclient.o .libs/smb_streams.o   -Wl,-rpath -Wl,/work/GIT/libsmbclient-php/.libs -Wl,-rpath -Wl,/work/GIT/libsmbclient-php/modules /work/GIT/libsmbclient-php/.libs/libsmbclient.so  -O2 -m64 -mtune=generic -Wl,-z -Wl,relro   -Wl,-soname -Wl,libsmbclient.so -o .libs/libsmbclient.so
    cc: error: /work/GIT/libsmbclient-php/.libs/libsmbclient.so: No such file or directory
    Makefile:188: recipe for target 'libsmbclient.la' failed
    make: *** [libsmbclient.la] Error 1

Ok, this can be workaround (make clean && make, and auto-provides filtering for downstream packaging)

Possible names:
* smb
* smbc
* smbclient (functions prefix)
* samba

**Comment by aklomp** [comment]
oops

**Comment by aklomp** [comment]
Yes, both the names 'libsmbclient-php' and 'libsmbclient' are not optimal. I'd vote for 'smbclient', which is the function prefix we picked on the PHP side.

This might be something for a 1.0 release, by the way.

**Comment by eduardok** [comment]
Well, this was annoying when I touched it back then, because I was also touching samba's code (libsmbclient). So, I would avoid using the same name. Perhaps smbclientphp? sambaphplib? heh
It would be nice if it were unique for google searches...

**Comment by remicollet** [comment]
"smbclient  php" already find this lib. as first entry ;)

**Comment by eduardok** [comment]
I think I was more concerned with having the same name as the samba one, but oh well, it is the nearly the same thing, except it is within PHP. I suppose we can stick to smbclient and go from there then.

**Comment by remicollet** [comment]
I can submit another PR for this, but have to wait for PR #23 to be merged first.

**Comment by icewind1991** [comment]
@DeepDiver1975 this will be relevant for our future packaging

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 this will be relevant for our future packaging

@jnweigert

**Comment by remicollet** [comment]
notice: for "extension_loaded" check, both the old name (libsmbclient) and the new one (smbclient) works (for now, compat stuff could be dropped later)

But the most important change is probably that the extension now support 'smb' streams.
