### ISSUE TITLE
no talloc stackframe around, leaking memory

### ISSUE THREAD

**Issue by remicollet** [eduardok/libsmbclient-php#24]
When running the test suite a notice this message

```
 no talloc stackframe around, leaking memory
```

Also present on travis build

After digging, I think this is a samba issue fixed in 4.2+
- Fedora 21 bug tracker: https://bugzilla.redhat.com/1261080
- RHEL-7 bug tracker https://bugzilla.redhat.com/1261107
- **Samba** bug tracker https://bugzilla.samba.org/show_bug.cgi?id=11177

Nothing which can be fixed in this project, only a tracker for people searching about this.

**Comment by aklomp** [comment]
Was also present in my private testing environment. Thanks for making the effort to report this upstream!

**Comment by eduardok** [comment]
Fixed upstream by Samba, closing.
