### ISSUE TITLE
smbclient-php IRC channel

### ISSUE THREAD

**Issue by eduardok** [eduardok/libsmbclient-php#27]
If you guys use IRC, please join me on freenode's #smbclient-php
I suppose we can pick another channel name if you guys prefer.

**Comment by eduardok** [comment]
Sorry aklomp, missed ya.
Anyway, I'll usually be there when you want to stop by :)

**Comment by aklomp** [comment]
Yeah, I'm not convinced that IRC is the best way for our small team to communicate. I personally prefer email or Github because they are asynchronous. But if you have time to chat, hit me up on email and we can arrange a session.

**Comment by eduardok** [comment]
oh, no, by no means I was suggesting it as proper means of communication. Typically OSS developers use IRC for random discussions, or just chit chat even. Mostly users looking for support or help will try IRC :)
I'll be there, so you can join whenever you feel like.
The github issues feature seem the best for feature requests and support.
