### ISSUE TITLE
Installing on windows system

### ISSUE THREAD

**Issue by pruimmartin** [eduardok/libsmbclient-php#31]
Hi! Does anybody know how to install this plugin on a windows system?
Thank you very much!

Regards,
Martin

**Comment by remicollet** [comment]
This extension rely on libsmbclient which only exists on non-windows system (and which doesn't make sense on Windows)

**Comment by eduardok** [comment]
What are you trying to run on Windows that would use libsmbclient-php, Martin ?

**Comment by eduardok** [comment]
Remi is right, what you want would have to be done at an upper level, although I can see some benefit of calling native Windows functions if it were ever built on Windows.

**Comment by eduardok** [comment]
Here is how to use it natively: http://stackoverflow.com/questions/1444976/accessing-a-windows-share-using-php
