### ISSUE TITLE
Installing on virtualbox ubuntu

### ISSUE THREAD

**Issue by pruimmartin** [eduardok/libsmbclient-php#32]
Hi Guys,

I've just installed a virtualbox ubuntu vm to test the libsmbclient.. I followed the installation instructions, but on the ./configure command, i receive the following error: 

checking for libsmbclient.h in default paths... not found
configure: error: Could not find libsmbclient.h

Does anyone know how to fix this?

Thanks!

**Comment by eduardok** [comment]
Please install package libsmbclient-dev then try again.
Regards

**Comment by pruimmartin** [comment]
Thanks! That worked like a charm!
