### ISSUE TITLE
Download file

### ISSUE THREAD

**Issue by pruimmartin** [eduardok/libsmbclient-php#33]
Hi,

How can i download a file? I am able to list the contents of a folder etc. but just want to download a simple file.

i can't manage to do this with smbclient_open or read.. 

Am i missing something?

Thanks!

**Comment by eduardok** [comment]
Go here https://github.com/eduardok/libsmbclient-php and check the examples at the bottom of the page.

**Comment by pruimmartin** [comment]
That is what i did, but i am only able to display a text file in the browser.. not download or open a file.. using the streams always gives me the error failed to open stream..

**Comment by pruimmartin** [comment]
Managed to do this now using the example, but adding: header("Content-Disposition: attachment; filename=\"$filename\";" );
