### ISSUE TITLE
Unable to install on El Capitan...

### ISSUE THREAD

**Issue by alfista-sk** [eduardok/libsmbclient-php#36]
Hi have downloaded your 0.7 and 0.8 version and I'm unable to install it.
After ./configure i have error:

Server-1:smbclient-0.8.0RC1 psadmin$ ./configure --enable-shared
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin15.2.0
checking host system type... x86_64-apple-darwin15.2.0
checking target system type... x86_64-apple-darwin15.2.0
checking for PHP prefix... /usr/local/Cellar/php55/5.5.31
checking for PHP includes... -I/usr/local/Cellar/php55/5.5.31/include/php -I/usr/local/Cellar/php55/5.5.31/include/php/main -I/usr/local/Cellar/php55/5.5.31/include/php/TSRM -I/usr/local/Cellar/php55/5.5.31/include/php/Zend -I/usr/local/Cellar/php55/5.5.31/include/php/ext -I/usr/local/Cellar/php55/5.5.31/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php55/5.5.31/lib/php/extensions/no-debug-non-zts-20121212
checking for PHP installed headers prefix... /usr/local/Cellar/php55/5.5.31/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable smbclient support... yes, shared
checking for libsmbclient support... yes, shared
checking for libsmbclient.h in default paths... not found
**configure: error: Could not find libsmbclient.h**

Please can you help me?

**Comment by remicollet** [comment]
Try

    ./configure --help

Especially

       --with-libsmbclient=DIR Installation prefix of libsmbclient.

**Comment by alfista-sk** [comment]
I tried also clean ./configure as you have it manual, and there is the same result.

I should use: ./configure --with-libsmbclient=DIR
There should be the DIR or I need change the DIR for a real directory path? And what path should be there?

**Comment by remicollet** [comment]
Of course... a real directory... where it will be able to find libsmbclient.h

**Comment by alfista-sk** [comment]
And can you tell me the directory where it should be, while i'm not so familiar with it and only know the extensions directories.

**Comment by remicollet** [comment]
I have absolutely no idea where this file is located on "your" computer.

**Comment by alfista-sk** [comment]
It isn't a part of your installation?
It is a part of the PHP?

**Comment by remicollet** [comment]
> It isn't a part of your installation?

No

>  It is a part of the PHP?

No

This is a library.

**Comment by alfista-sk** [comment]
OK I found it and use it so with config command:

./configure --enable-shared --with-libsmbclient=/usr/local/Cellar/samba/3.6.25/include/

and all was done correctly. But when I used make command I have this error:

fatal error: 'libsmbclient.h' file not found
#include <libsmbclient.h>
         ^
1 error generated.
make: *** [smbclient.lo] Error 1

**Comment by remicollet** [comment]
Try:

     ./configure --enable-shared --with-libsmbclient=/usr/local/Cellar/samba/3.6.25

**Comment by alfista-sk** [comment]
I try it, but now I have this error:

cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/smbclient.so -bundle  .libs/smbclient.o .libs/smb_streams.o  -L/usr/local/Cellar/samba/3.6.25//lib -lsmbclient  -Wl,-rpath -Wl,/usr/local/Cellar/samba/3.6.25//lib
duplicate symbol _php_stream_smb_wrapper in:
    .libs/smbclient.o
    .libs/smb_streams.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [smbclient.la] Error 1

**Comment by remicollet** [comment]
Try to change in php_smbclient.h (around line 114)

     extern php_stream_wrapper php_stream_smb_wrapper;

**Comment by alfista-sk** [comment]
Yes this correction is working, but still can see it after installing. :-(

**Comment by eduardok** [comment]
You don't see it listed on phpinfo() ?
Open your php.ini and check where your extensions_dir point to (or perhaps that shows in phpinfo() too).

**Comment by alfista-sk** [comment]
I have test it over command: php -m, and php -i
I see where the extension where is placed directly over terminal, but in php not. Its in a standard extension folder:
/usr/lib/php/extensions/no-debug-non-zts-20121212

I have looked in older system and I found that i have there two extensions libsmbclient.so and smbclient.so and on old system (OS X 10.10) was it working but on new one (OS X 10.11) not.

**Comment by eduardok** [comment]
This is old, so if @alfista-sk is still having issues, please update status to reopen.
