### ISSUE TITLE
Conflicts with mongodb extension

### ISSUE THREAD

**Issue by remicollet** [eduardok/libsmbclient-php#39]
Running some debug, I discover some segfault issues when both extensions are loaded.

This is related fo sasl_client_done() called during process shutdown
More on https://jira.mongodb.org/browse/PHPC-658

For now, workaround is to load smbclient "before" mongodb.

**Comment by eduardok** [comment]
hmmm, what it the source for php-pecl-mongodb-1.1.5 ? Is it their https://github.com/mongodb/mongo-php-driver.git or https://github.com/mongodb/mongo-php-driver-legacy.git ?
Still, no 1.1.5 tag...

**Comment by remicollet** [comment]
=> https://pecl.php.net/package/mongodb
so => https://github.com/mongodb/mongo-php-driver

**Comment by eduardok** [comment]
I saw on https://bugzilla.redhat.com/show_bug.cgi?id=1381958 that it affects not only this library, so I'll close until someone reports this again (if ever).
