### ISSUE TITLE
configure: error: Could not find libsmbclient.h

### ISSUE THREAD

**Issue by Zjemm** [eduardok/libsmbclient-php#42]
When trying to install i got:
configure: error: Could not find libsmbclient.h

some day's earlier, it worked fine, something changed?

wanted to reinstall because php had trouble loding it:
PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/smbclient.so' - /usr/lib/php5/20131226/smbclient.so: undefined symbol: zend_list_close in Unknown on line 0

it seems the libsmbclient-php is dependend on php7 stuff
i found a debian package: https://packages.debian.org/stretch/php-smbclient

but it only installs it in the php7 folders
when i copy it to the php5 folders it won't load it.
how can i get php5 to also load the version 7 externtions?

**Comment by eduardok** [comment]
You need to install package libsmbclient-dev. That is the package that provides libsmbclient.h.
