### ISSUE TITLE
PHP Startup: Unable to load dynamic library /usr/lib/php5/20121212/smbclient.so

### ISSUE THREAD

**Issue by jedunbar** [eduardok/libsmbclient-php#44]
Hello,

I recently installed ownCloud 9.1.1 on a 14.04.5 installation. I followed the libsmbclient-php instructions here: https://github.com/eduardok/libsmbclient-php/ to get SMB shares to work. I also had to install libsmbclient-dev to get past a missing file error. As it stands, I have the following issues...

1) The instructions didn't cite which php.ini to add extension="smbclient.so", so I assumed /etc/php5/cli/php.ini was the correct one. Is this correct? I have the 5 different ones: /etc/php5/apache2/php.ini, /etc/php5/cli/php.ini, /usr/share/php5/php.ini-dev, /usr/share/php5/php.ini-production and /usr/share/php5/php.ini-production.cli

2) After adding extension="smbclient.so" to /etc/php5/cli/php.ini, I get the following PHP error: PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/smbclient.so' - /usr/lib/php5/20121212/smbclient.so: cannot open shared object file: No such file or directory in Unknown on line 0.

3) An obvious side effect of the above two issues is that I cannot access SMB shares via ownCloud. I get the following error when trying to access any shares via the web: "Storage not available" and the folder is empty.

Thoughts? Thanks all.

**Comment by aklomp** [comment]
1) This is more of a general Ubuntu/OwnCloud question, and I'm not too familiar with either, so maybe there's a better answer somewhere else. From the looks of it, `/etc/php5/cli/php.ini` might not be the right file. The `cli` stands for 'commandline interface' and is the config that is loaded when a PHP program is run from the commandline as a regular application. If you're running PHP as an Apache module, which I guess is required for OwnCloud, you'll probably want `/etc/php5/apache2/php.ini`, or one of the other ones that doesn't have 'cli' in the name.

2) PHP is looking for the extension in the mentioned directory, but it doesn't exist in that location. No such file or directory. You probably need to move or symlink your `smbclient.so` to that location.

**Comment by eduardok** [comment]
Closing given lack of feedback, and likeliness of no-issue in our side.
