### ISSUE TITLE
Incorrect function definition for smbclient_read

### ISSUE THREAD

**Issue by icewind1991** [eduardok/libsmbclient-php#47]
The [function definition](https://github.com/eduardok/libsmbclient-php/blob/cf9259f563097cecdb7f84d8127ec009fdff90c7/smbclient.c#L271) defines only 2 parameters (state and file) while the [implementation](https://github.com/eduardok/libsmbclient-php/blob/cf9259f563097cecdb7f84d8127ec009fdff90c7/smbclient.c#L1324) (and documentation) use 3 parameters (state, file and count)

I'm not sure if this has any behavioral effects but it causes reflection to report an invalid number of parameters which in turns trips static code analysers

**Comment by remicollet** [comment]
Good catch...
