### ISSUE TITLE
Error 13 (Permission Denied) with PECL krb5 since version 1.1.1

### ISSUE THREAD

**Issue by ccpp** [eduardok/libsmbclient-php#49]
After obtaining a valid Kerberos ticket with PECL krb5, a call to `smbclient_stat('smb://host/share/')` returns error code 13 for access.

Using the same ticket cache file on command line, access to the network share works:

    KRB5CCNAME=/tmp/(...)/krb5cc smbclient -k //host/share/
    OS=[Windows Server 2008 R2 Standard 7601 Service Pack 1] Server=[Windows Server 2008 R2 Standard 6.1]
    smb: \> ls
      .                                   D        0  Sun Oct 23 16:32:19 2016
      ..                                  D        0  Sun Oct 23 16:32:19 2016
    (...)

-> I *can* browse the share; the kerberos cache file is the same one created using PECL krb5 1.1.1, so the bug is not necessarily in this library!

After downgrading PECL krb5 to 1.1.0, libsmbclient-php has access to the share.
I do not know if the bug is in the KRB5 library or in libsmbclient-php

**Comment by eduardok** [comment]
Please try with release 0.9.0, and let us know.
Thanks.

**Comment by ccpp** [comment]
Even after an upgrade of php-pecl-krb5 to 1.1.2 nothing changed (specifically, php-pecl-krb5.x86_64 0:1.1.2-3.el7.remi.5.6)

**Comment by ccpp** [comment]
Update: even a manual downgrade to krb5-1.1.0 did not help, so that probably was not even the root cause
