### ISSUE TITLE
Stable 0.9 release containing Remis performance fixes

### ISSUE THREAD

**Issue by ralfbecker** [eduardok/libsmbclient-php#50]
Is there an ETA for a new stable release, or if not what are the blockers?

I'm asking as Remis fixes make the extension for my usable performance-wise.

Ralf

**Comment by eduardok** [comment]
I will proceed with that change.

**Comment by remicollet** [comment]
@eduardok please check pr #48 before release

**Comment by eduardok** [comment]
@remicollet would you take a look at my last commit before we tag it? Seems enough to me given that 0.9.0dev didn't make it to PECL.

**Comment by remicollet** [comment]
@eduardok changes ok, perhaps better changelog entries (since last 0.8.0 release on pecl)

- fix gh#47  Incorrect function definition for smbclient_read
- optimization: enable stream wrapper reusing connections

**Comment by remicollet** [comment]
@eduardok FYI, i just add the extension in **centos-sclo-sclo** repopsitory (testing for now)

More information:
* https://blog.remirepo.net/post/2017/02/23/Additional-PHP-packages-for-RHSCL
* https://www.redhat.com/archives/sclorg/2017-March/msg00008.html

@ralfbecker as SCL are the official and supported way to install recent PHP versions (5.6/7.0) on RHEL, can you please check if everything EGroupware needs is there, else contact me to see what I can do (by mail, as probably out-of-topic here)
