### ISSUE TITLE
OS X 10.12 Build

### ISSUE THREAD

**Issue by OllieB** [eduardok/libsmbclient-php#51]
Can't see what I'm doing wrong. Tried to follow the advice given in #36 but to no avail.

`cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/smbclient.so -bundle  .libs/smbclient.o .libs/smb_streams.o  -L/usr/local/Cellar/samba/3.6.25//lib -lsmbclient  -Wl,-rpath -Wl,/usr/local/Cellar/samba/3.6.25//lib
duplicate symbol _php_stream_smb_wrapper in:
    .libs/smbclient.o
    .libs/smb_streams.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [smbclient.la] Error 1
`

I've tried 0.8 and 0.9, same issue. Any ideas? Thanks!

**Comment by remicollet** [comment]
Please try fix from #52

**Comment by OllieB** [comment]
That works great, thanks!

**Comment by remicollet** [comment]
Please keep this issue open until the fix is merged (and the merge will auto-close it)

**Comment by OllieB** [comment]
Apologies!

**Comment by OllieB** [comment]
Having gotten it to build, it's throwing me errors when I try and use it.

Building with:
```
phpize
./configure CFLAGS="-arch i386" LDFLAGS="-arch i386" --enable-shared --with-libsmbclient=/usr/local/Cellar/samba/3.6.25/include/ --with-php-config=/Applications/AMPPS/php-5.6/bin/php-config
make
cp modules/smbclient.so /Applications/AMPPS/php-5.6/lib/extensions/ext
```

Errors:
```
[Wed Feb 22 09:47:23.495356 2017] [core:notice] [pid 77874] AH00052: child pid 77888 exit signal Abort trap (6)
dyld: lazy symbol binding failed: Symbol not found: _smbc_new_context
  Referenced from: /Applications/AMPPS/php-5.6/lib/extensions/ext/smbclient.so
  Expected in: flat namespace

dyld: Symbol not found: _smbc_new_context
  Referenced from: /Applications/AMPPS/php-5.6/lib/extensions/ext/smbclient.so
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: _smbc_new_context
  Referenced from: /Applications/AMPPS/php-5.6/lib/extensions/ext/smbclient.so
  Expected in: flat namespace

dyld: Symbol not found: _smbc_new_context
  Referenced from: /Applications/AMPPS/php-5.6/lib/extensions/ext/smbclient.so
  Expected in: flat namespace
```

Any ideas?

**Comment by remicollet** [comment]
I don't know OS X, but looks like you are linked against the light library version,
CFLAGS option looks strange, should use configure options instead

**Comment by OllieB** [comment]
I haven't been able to find any other way to set the architecture to i386. It defaults to building x86_64, which, sadly, is no use to me. I'll have a look at the configure options, see what I can find.

**Comment by OllieB** [comment]
Tried using --build=i386 instead of the CFLAGS, and it appears to build happily, but I get a libsmbclient.a file instead of the smbclient.so I was hoping for... Strange...

**Comment by eduardok** [comment]
Perhaps it is building statically only because you already depend on other static libraries?

**Comment by OllieB** [comment]
Not sure what that means... Building on OSX is less than ideal now Samba isn't included with the OS. Any advice you can offer is much appreciated, but you've already done so much with this extension, I feel bad to ask!
