### ISSUE TITLE
Error While Running ./configure

### ISSUE THREAD

**Issue by Kkumarsantosh** [eduardok/libsmbclient-php#59]
Hello, 

When i execute the command ./configure it will show an error as 

==================================

checking for libsmbclient support... yes, shared
checking for libsmbclient.h in default paths... not found
configure: error: Could not find libsmbclient.h

=================================

Please help to let me know does it also need some other client as well to install. or Which PHP version.
Currently i have php 5.6

**Comment by remicollet** [comment]
>  checking for libsmbclient.h in default paths... not found

Obviously development package for libsmbclient is missing.
The name and installation vary with used distribution.

**Comment by Kkumarsantosh** [comment]
How to install that can you help yo provide me with the steps?

**Comment by Kkumarsantosh** [comment]
I have smbclient installed with Version 3.6.9-168.el6_5
and i found that libsmbclient.h are also available in /usr/local/samba/include/libsmbclient.h

**Comment by remicollet** [comment]
On RHEL / CentOS 6, you need to install **libsmbclient-devel**

And probably simpler to use a RPM repostiory providing PHP version and extensions you need.... 
e.g. https://rpms.remirepo.net/wizard/

**Comment by eduardok** [comment]
No comments from @Kkumarsantosh , and we have no indication of build-wise issues, closing.

**Comment by abulhol** [comment]
+1 On Ubuntu 18, you have to install `libsmbclient-dev`

**Comment by eduardok** [comment]
> +1 On Ubuntu 18, you have to install `libsmbclient-dev`

Yes, if you want to build from code you need to install the required header files, I'll put this on the docs.

**Comment by abulhol** [comment]
Thanks @eduardok !

**Comment by Mica-CRT** [comment]
Hi! can i install "libsmbclient-dev" on VOID-LINUX? which use XBPS as package manager, i tried but with no results :(

**Comment by eduardok** [comment]
> Hi! can i install "libsmbclient-dev" on VOID-LINUX? which use XBPS as package manager, i tried but with no results :(

Try:
```
xbps-install -Su libsmbclient
xbps-install -Su libsmbclient-devel
```

**Comment by Mica-CRT** [comment]
Thanks for the reply! I tried running these two commands, the first output me a list of broken events due to many unresolvable shlib, the second print me that "libsmbclient-devel" it's not found in repository pool

**Comment by Mica-CRT** [comment]
Should i add a new repo into my xbps tool?
