### ISSUE TITLE
How to get file owner (SID)

### ISSUE THREAD

**Issue by henrywood** [eduardok/libsmbclient-php#62]
Is it possible to get the file owner - either as a SID or string.

If so, how ?

If not, is this something that can be added ?

If I do var_dump(fileowner('smb://fileserver/share/file1.txt'));
then I just get "int(0)" as output - presume that is to tell me that "root" user owns the file, but this is not correct... I need the Windows/AD user...

Thanks in advance !

**Comment by mstrucken** [comment]
You can get acls using `smbclient_getxattr`:
```
$uri = 'smb://fileserver/share/file1.txt';
$xattr = smbclient_getxattr( $state, $uri, 'system.nt_sec_desc.acl.*' );
```

**Comment by henrywood** [comment]
Thank you very much !
