### ISSUE TITLE
Apache segfault DFSR share

### ISSUE THREAD

**Issue by VamPikmin** [eduardok/libsmbclient-php#67]
I've been having an issue with some of the files on a smb dfsr share. Can't quite narrow it down but it doesn't seem to be a permission issue, I can access the file fine in windows 

I used the Dump a file to standard output to test this:

`[Fri Apr 05 08:25:24.096494 2019] [core:notice] [pid 28400] AH00051: child pid 28976 exit signal Segmentation fault (11), possible coredump in /etc/apache2`

I don't really know how to get more info on why it's happening.
Thanks

php-smbclient:
  Installed: 0.8.0~rc1-2build1
  Candidate: 0.8.0~rc1-2build1
  Version table:
 *** 0.8.0~rc1-2build1 500
        500 http://au.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     0.8.0~rc1-2 500
        500 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

**Comment by eduardok** [comment]
Too old by now, you'd have to be able to reproduce it on the latest release.
