### ISSUE TITLE
how to get php-smbclient 1.0 in debian?

### ISSUE THREAD

**Issue by Rello** [eduardok/libsmbclient-php#68]
Hello,

I still have the issue that debian wants to install php 7.2 dependencies - but I am on php 7.3
`php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-phpdbg php7.2-readline`

but debian only provides your 0.9.0.3 version
https://packages.debian.org/de/source/sid/php-smbclient

any suggestion?
thank you very much for your support!

**Comment by remicollet** [comment]
This is obviously not a bug for this project, but a debian one.

**Comment by Rello** [comment]
Hello,

its available in the new bullseye release. buster is not changed anymore...
