### ISSUE TITLE
Provide Red Hat spec file

### ISSUE THREAD

**Issue by eduardok** [eduardok/libsmbclient-php#7]
Would be nice if we had a spec file so people can build RPMS right-away.

**Comment by remicollet** [comment]
FYI, a Fedora / RHEL / CentOS / RHSCL specfile is available in
https://github.com/remicollet/remirepo/tree/master/php/php-libsmbclient

(and of course RPM packages are available in http://rpms.remirepo.net/ )

**Comment by eduardok** [comment]
Cool, I'll try hard to get back to helping develop it (starting with exposing remote password change in samba's libsmbclient).
Merci beaucoup.

**Comment by remicollet** [comment]
[php-smbclient](https://apps.fedoraproject.org/packages/php-smbclient) is now part official Fedora and EPEL repositories (RHEL / CentOS), this can be probably closed.
