### ISSUE TITLE
Strange behavior with smbclient_getxattr

### ISSUE THREAD

**Issue by theroch** [eduardok/libsmbclient-php#72]
We have one Ubuntu Server 16.04 with php 7.3, smbclient 4.3.11 and php-smbclient 1.0.0 and an other server with Ubuntu Server 18.04 with php 7.4., smbclient v4.10.15 and php-smbclient v1.0.0.

There is also an debian 10.3 with Samba 4.9.5, php-smbclient 0.9.0 where the mode returns 0x10.

On the 16.04 system smbclient_getxattr returns for a directory the mode 0x10 on the 18.04 system it returns for a directory the mode 0x41ed.

The mode is read with this code:
smbclient_getxattr($state, $uri, 'system.dos_attr.*');

My code to read the mode is:
```
<?php
$workgroup ='your workgroup or domain';
$user           ='your user';
$pwd           = 'your secret password';
$uri             = 'smb://your.server.local/share';
// Create new state:
$state = smbclient_state_new();
// Initialize the state with workgroup, username and password:
smbclient_state_init($state, $workgroup, $user, $pwd);

$attr = @smbclient_getxattr($state, $uri, 'system.dos_attr.*');
var_dump($attr);
```
I don't understand where the 0x41ed comes from.
I've also checked your source and the source from samba but didn't find anything.
I think this problem is related to an smb configuration, but don't know which it can be?
Maybe you can point me to the right direction or solve my problem?

**Comment by theroch** [comment]
This bug is related to [Nextcloud issue 20622](https://github.com/nextcloud/server/issues/20622)

**Comment by theroch** [comment]
See also [icewind1991/SMB/issues/90](https://github.com/icewind1991/SMB/issues/90)

**Comment by eduardok** [comment]
I understand the issue, but I've confirmed it is not related to this library, after all, we don't do anything fancy with the values returned from libsmbclient. Closing.

**Comment by jvillafanez** [comment]
@eduardok sorry to revive an old thread, but I'm having a similar problem. File attributes cannot be fetched properly for directories through the getxattr method.
I understand it isn't this library's fault, but is there any other alternative that can be used? Any way to know whether a directory is hidden or not (using libsmbclient 4.11+)?
