### ISSUE TITLE
Hand over a command line option

### ISSUE THREAD

**Issue by mmattel** [eduardok/libsmbclient-php#77]
Hello @eduardok 

this may be a stupid question to you, but is is possible (since when, and how) to handover the command line option `-m NT1` as you could do when just using smbclient on the command line? I have not read this in the readme

Note: it is a difference using a option in smb.conf which is valid for all connections compared to use an option for a particular connection. Using it in smb.conf may give access to one server but disables others.

Many thanks.

**Comment by eduardok** [comment]
I've just released 1.0.2 on PECL as I'm confident it won't cause issues. Will add more details on issue 53.
