### ISSUE TITLE
how to compile it for windows

### ISSUE THREAD

**Issue by ptogladif** [eduardok/libsmbclient-php#88]
could you create config.w32 ??

i really need it to compile it and add this extension to php 8 on windows server

thanks

**Comment by thirdwheel** [comment]
It would be useful even if it just encapsulated the Windows SMB functionality into a smb:// stream handler for cross platform compatible code. You could do this in pure PHP, though.

https://php.net/stream_wrapper_register

**Comment by eduardok** [comment]
It is unlikely that it will be compiled on Windows considering that it depends on libsmbclient.
