### ISSUE TITLE
php-fpm won't start error related to smbclient

### ISSUE THREAD

**Issue by xavier8854** [eduardok/libsmbclient-php#93]
Hi, 
After an upgrade from php 7.3 to php 8.0, I cannot restart php-fpm :
```
[root@numenor php80]# service php-fpm restart
Performing sanity check on php-fpm configuration:
<br />
<b>Fatal error</b>:  Duplicate parameter name $oldstate for function smbclient_rename() in <b>Unknown</b> on line <b>0</b><br />
```
Digging into the code I noted effectively a duplicate parameter here :
https://github.com/eduardok/libsmbclient-php/blob/master/smbclient.c#L189
I don't know if it is the cause of my error. Is this intended or a typo ?
Thanks for clarification
Regards
Xavier

**Comment by remicollet** [comment]
I confirm the issue.

Preparing a huge PR about arginfo, found 2 other minor issues

- smbclient_chmod : mode is required
- smbclient_utimes: time and time are optional

**Comment by remicollet** [comment]
Please check PR #94  which fix this issue and improve extension reflection.

**Comment by remicollet** [comment]
Notice: this error is only raised when using **debug build**, so nobody should be affected (excepted dev. using this mode for very specific debugging purposes on php sources).

https://github.com/php/php-src/blob/PHP-8.0/Zend/zend_API.c#L2461

BTW, still a issue and need to be fixed (ex: won't be possible to call this function using named parameters)
