### ISSUE TITLE
Not working with Samba 4.17.5

### ISSUE THREAD

**Issue by Ryushin** [eduardok/libsmbclient-php#98]
So I noticed this morning that Nextcloud was not working with external smb storage after Samba was upgraded to 4.17.5 on Debian Bullseye.  Others have reported this as well, but from CentOS.
https://www.spinics.net/lists/centos/msg181966.html

I tried recompilng libsmclient-php against 4.17.5 but it did not fix the problem.

**Comment by bnerickson** [comment]
Might be related to this: https://bugzilla.samba.org/show_bug.cgi?id=14808

**Comment by BenzinoNapoloni** [comment]
What about using `strlen(values)` to determine the length of the string in the char-array "values" (file smbclient.c, line 1685)? Here is a suggestion for a patch: [smbclient.patch.txt](https://github.com/eduardok/libsmbclient-php/files/10843385/smbclient.patch.txt)

I've tested the patch with my own Nextcloud server and it seems to work correctly so far. Or are there any drawbacks which I haven't considered?

**Comment by sempervictus** [comment]
@BenzinoNapoloni: Thank you, might be worth putting that into a pull request - seems to work at first glance, but proper review and wide testing benefit from visibility/merge.

**Comment by eduardok** [comment]
Please try with release 1.0.7, or even 1.1.0, and let us know if it is still an issue.

**Comment by remicollet** [comment]
Digging deeper, 

This is a regression in samba 4.16.9 and 4.17.5

Reported this to Fedora maintainer (with more explanation)
https://bugzilla.redhat.com/show_bug.cgi?id=2183951

I will try to find a way to workaround this...

**Comment by remicollet** [comment]
Feedback on pr #100 welcome

**Comment by theroch** [comment]
I've tried it with:
Samba 4.18.1
libsmbclient 1.1.0
PHP 7.4.x

But I get only a empty string for all xattr.

**Comment by theroch** [comment]
Thx to @eduardok he released version [1.1.1](https://github.com/eduardok/libsmbclient-php/releases/tag/1.1.1) with the fix.
The release is also available via [pecl](https://pecl.php.net/package/smbclient)
